const IPC = {
  getInitData: () => window.OpsLynk.getInitData(),
  getAppMode: () => window.OpsLynk.getAppMode(),
  sendChat: data => window.OpsLynk.sendChat(data),
  sendFileOffer: data => window.OpsLynk.sendFileOffer(data),
  sendBroadcast: data => window.OpsLynk.sendBroadcast(data),
  sendBroadcastReply: data => window.OpsLynk.sendBroadcastReply(data),
  sendHelpRequest: data => window.OpsLynk.sendHelpRequest(data),
  ackHelp: data => window.OpsLynk.ackHelp(data),
  exportPeerSpecs: data => window.OpsLynk.exportPeerSpecs(data),
  saveUserGroup: data => window.OpsLynk.saveUserGroup(data),
  deleteUserGroup: data => window.OpsLynk.deleteUserGroup(data),
  updateProfile: data => window.OpsLynk.updateProfile(data),
  selectAvatar: () => window.OpsLynk.selectAvatar(),
  lockAllScreens: data => window.OpsLynk.lockAllScreens(data),
  unlockAllScreens: () => window.OpsLynk.unlockAllScreens(),
  captureScreenshotPreview: () => window.OpsLynk.captureScreenshotPreview(),
  requestPeerScreenshot: data => window.OpsLynk.requestPeerScreenshot(data),
  getDeviceId: () => window.OpsLynk.getDeviceId?.(),
  minimize: () => window.OpsLynk.minimize(),
  maximize: () => window.OpsLynk.maximize(),
  close: () => window.OpsLynk.close(),
  setMainWindow: () => window.OpsLynk.setMainWindow?.(),
  selectVideoBroadcastFile: () => window.OpsLynk.selectVideoBroadcastFile(),
  sendForcedVideoBroadcast: data => window.OpsLynk.sendForcedVideoBroadcast(data),
  stopForcedVideoBroadcast: () => window.OpsLynk.stopForcedVideoBroadcast(),
  auth: {
    listUsers: () => window.OpsLynk.auth.listUsers(),
    createUser: data => window.OpsLynk.auth.createUser(data),
    deleteUser: data => window.OpsLynk.auth.deleteUser(data)
  },
  on: (channel, handler) => window.OpsLynk.on(channel, handler),
  once: (channel, handler) => window.OpsLynk.once(channel, handler)
};
